In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
# Creating the model with the keras library. 

# You can create a sequential model by passing a list of layer instances to the constructor. 

model = Sequential()
model.add(Dense(32, activation='relu',input_shape=(500,)))
model.add(Dense(10))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 32)                16032     
_________________________________________________________________
dense_16 (Dense)             (None, 10)                330       
Total params: 16,362
Trainable params: 16,362
Non-trainable params: 0
_________________________________________________________________


In [21]:
#Next comes the compilation

model.compile(optimizer='rmsprop',
             loss = 'binary_crossentropy',
             metrics= ['accuracy'])

In [22]:
# NExt step is to train the model 

model = Sequential()
model.add(Dense(32, activation = 'relu', input_dim = 100))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
             loss = 'binary_crossentropy',
             metrics= ['accuracy'])



In [23]:
# Generate the data (dummy)

import numpy as np
data = np.random.random((1000,100))
labels = np.random.randint(2,size = (1000,1))

In [24]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 32)                3232      
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 33        
Total params: 3,265
Trainable params: 3,265
Non-trainable params: 0
_________________________________________________________________


In [25]:
# Fitting the model

model.fit(data,labels,batch_size = 32, epochs = 10, verbose=2,
         validation_split=0.2,
         shuffle =True)

Train on 800 samples, validate on 200 samples
Epoch 1/10
 - 0s - loss: 0.7037 - acc: 0.4987 - val_loss: 0.7007 - val_acc: 0.5200
Epoch 2/10
 - 0s - loss: 0.6904 - acc: 0.5262 - val_loss: 0.6916 - val_acc: 0.5200
Epoch 3/10
 - 0s - loss: 0.6851 - acc: 0.5375 - val_loss: 0.6965 - val_acc: 0.5100
Epoch 4/10
 - 0s - loss: 0.6772 - acc: 0.5600 - val_loss: 0.7057 - val_acc: 0.4900
Epoch 5/10
 - 0s - loss: 0.6717 - acc: 0.5787 - val_loss: 0.6930 - val_acc: 0.5300
Epoch 6/10
 - 0s - loss: 0.6654 - acc: 0.5900 - val_loss: 0.6946 - val_acc: 0.5300
Epoch 7/10
 - 0s - loss: 0.6579 - acc: 0.6150 - val_loss: 0.6931 - val_acc: 0.5300
Epoch 8/10
 - 0s - loss: 0.6545 - acc: 0.6275 - val_loss: 0.6941 - val_acc: 0.5450
Epoch 9/10
 - 0s - loss: 0.6476 - acc: 0.6375 - val_loss: 0.6926 - val_acc: 0.5400
Epoch 10/10
 - 0s - loss: 0.6433 - acc: 0.6262 - val_loss: 0.6929 - val_acc: 0.5250


In [26]:
# Evaluate the model. 

model.evaluate(data,labels,batch_size = 32, 
               verbose = 1, sample_weight = None)

1000/1000 [==============================] - 0s 50us/step


[0.64388278150558476, 0.63]

In [27]:
# You can predict the new data labels
model.predict(data,batch_size = 32,verbose =1)

1000/1000 [==============================] - 0s 48us/step


array([[ 0.4529852 ],
       [ 0.46959141],
       [ 0.39405686],
       [ 0.65664554],
       [ 0.49885893],
       [ 0.42133364],
       [ 0.43367288],
       [ 0.46001071],
       [ 0.57091701],
       [ 0.58384758],
       [ 0.41782352],
       [ 0.30989331],
       [ 0.44458294],
       [ 0.48055482],
       [ 0.47427037],
       [ 0.33988675],
       [ 0.59462017],
       [ 0.49021453],
       [ 0.65280879],
       [ 0.27595788],
       [ 0.47218561],
       [ 0.47852761],
       [ 0.65750229],
       [ 0.4639414 ],
       [ 0.76692736],
       [ 0.41904849],
       [ 0.3219651 ],
       [ 0.44823271],
       [ 0.53975487],
       [ 0.47560722],
       [ 0.5510602 ],
       [ 0.68878776],
       [ 0.37369493],
       [ 0.42887571],
       [ 0.56355751],
       [ 0.4863508 ],
       [ 0.49514747],
       [ 0.50629681],
       [ 0.51580137],
       [ 0.58115053],
       [ 0.61698627],
       [ 0.46804783],
       [ 0.57663602],
       [ 0.41130152],
       [ 0.53762197],
       [ 0

In [28]:
# We can predict classes. 

model.predict_classes(data,batch_size = 32,verbose =1)

1000/1000 [==============================] - 0s 35us/step


array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
    

In [30]:
# Ypu can predict the prob which is the same as the first one 

model.predict_proba(data,batch_size = 32, verbose = 1)

1000/1000 [==============================] - 0s 27us/step


array([[ 0.4529852 ],
       [ 0.46959141],
       [ 0.39405686],
       [ 0.65664554],
       [ 0.49885893],
       [ 0.42133364],
       [ 0.43367288],
       [ 0.46001071],
       [ 0.57091701],
       [ 0.58384758],
       [ 0.41782352],
       [ 0.30989331],
       [ 0.44458294],
       [ 0.48055482],
       [ 0.47427037],
       [ 0.33988675],
       [ 0.59462017],
       [ 0.49021453],
       [ 0.65280879],
       [ 0.27595788],
       [ 0.47218561],
       [ 0.47852761],
       [ 0.65750229],
       [ 0.4639414 ],
       [ 0.76692736],
       [ 0.41904849],
       [ 0.3219651 ],
       [ 0.44823271],
       [ 0.53975487],
       [ 0.47560722],
       [ 0.5510602 ],
       [ 0.68878776],
       [ 0.37369493],
       [ 0.42887571],
       [ 0.56355751],
       [ 0.4863508 ],
       [ 0.49514747],
       [ 0.50629681],
       [ 0.51580137],
       [ 0.58115053],
       [ 0.61698627],
       [ 0.46804783],
       [ 0.57663602],
       [ 0.41130152],
       [ 0.53762197],
       [ 0